# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 330599fb5a6d46601afefacb5ffc2ea37e1169458778180f8819343cf4849a66d03f1c6925bfb569263729cf84fa5c469e228a115ac155f7f0aafd2e0299f49b

test:
  secret_key_base: e19ed569c521ba4f84a2e138a20bfa7f9444a317e1fe83bf6eb171c6ebba38cb5b50798c80b67e69ddc859c6fb5ddaab332ddf4eef432ebf79a4149fe9fffb0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
